
server:
  port: 5544
  
spring:
  application:
    name: DEV ENVIRONMENT
  security:
    user:
      name: sting
      password: sting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cachedDb?createDatabaseIfNotExist=true
    username: root
    password: boss
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  data:
    jpa:
      repositories:
        enabled: true